{% set name = "drekar-launch" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/johnwason/drekar-launch.git
  git_rev: {{ version }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - appdirs
    - jinja2
    - pyyaml
    - drekar-launch-process
  run:
    - python >=3.6
    - appdirs
    - jinja2
    - pyyaml
    - drekar-launch-process
    
test:
  requires:
    - pytest
    - pywin32  # [win]
  source_files:
    - test/
  imports:
    - pytest
  commands:
    - pytest test/ --verbose

about:
  home: https://github.com/johnwason/drekar-launch
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A simple launcher for Robotics applications

extra:
  recipe-maintainers:
    - johnwason
